# Use a Miniconda base image
FROM continuumio/miniconda3

SHELL ["/bin/bash", "-c"]

# Set non-interactive mode to avoid prompts during package installation
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y --no-install-recommends build-essential git fish && rm -rf /var/lib/apt/lists/*

COPY . ./

#RUN apt-get update && apt-get install -y --no-install-recommends gdal-bin libgdal-dev python3-gdal libboost-program-options-dev

RUN conda create -n gwarp_pp python=3.10 -y

#RUN conda activate gwarp_pp && bash compile.sh

RUN conda run -n gwarp_pp conda install --channel=conda-forge --quiet --yes gdal=3.6.2

RUN conda run -n gwarp_pp bash compile.sh

RUN conda run -n gwarp_pp conda install pyproj scipy conda-forge::opencv

#RUN conda run -n gwarp_pp apt-get update && apt-get install -y libboost-program-options-dev
RUN conda run -n gwarp_pp conda install -c conda-forge boost=1.82.0

RUN echo ". activate gwarp_pp" >> ~/.bashrc
#RUN apt install -y xvfb
RUN apt-get update && apt-get install -y libgl1-mesa-glx libglib2.0-0 && rm -rf /var/lib/apt/lists/*

# Set the default shell to bash and activate Conda environment
SHELL ["/bin/bash", "-c", "source activate gwarp_pp && bash"]
RUN conda init bash && conda info --envs
